repos:
  - repo: local
    hooks:
      - id: optimize-png
        name: Optimize PNG images
        entry: bash
        language: system
        files: \.png$
        pass_filenames: true
        args:
          [
            -c,
            'for file in "$@"; do scripts/optimize-images.sh "$file"; done && git add "$@"',
          ]
